/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package naqiku.applicationPopups;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import naqiku.application.Config;
import naqiku.application.transaksiForm;

/**
 *
 * @author Susa
 */
public class popupTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form popupTransaksi
     */
    public popupTransaksi() {
        initComponents();
        this.setLocationRelativeTo(null);
        tampilDeskripsi();
    }

    private void tampilDeskripsi(){
        String sql = "SELECT nama_barang, warna_barang, harga_jual FROM barang WHERE kd_barang = '"+transaksiForm.kd_barang+"';";
        
        try {
            ResultSet rs = Config.ambilData(sql);
            if (rs.next()) {
                warnaBarang.setText(rs.getString(1));
                namaBarang.setText(rs.getString(2));
                hargaBarang.setText(rs.getString(3));
            }
        } catch (Exception e) {
             System.out.println("Error View data : " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hargaBarang = new javax.swing.JLabel();
        namaBarang = new javax.swing.JLabel();
        warnaBarang = new javax.swing.JLabel();
        jumlahBarang = new javax.swing.JLabel();
        jumlahKurang = new javax.swing.JLabel();
        jumlahTambah = new javax.swing.JLabel();
        btn_batal = new javax.swing.JLabel();
        btn_barang = new javax.swing.JLabel();
        frameBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 376));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hargaBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hargaBarang.setText("HARGA");
        hargaBarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hargaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 200, -1));

        namaBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaBarang.setText("NAMA");
        namaBarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(namaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 200, -1));

        warnaBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warnaBarang.setText("WARNA");
        warnaBarang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(warnaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 200, -1));

        jumlahBarang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jumlahBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahBarang.setText("1");
        getContentPane().add(jumlahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 60, 10));

        jumlahKurang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jumlahKurangMouseClicked(evt);
            }
        });
        getContentPane().add(jumlahKurang, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 30, 30));

        jumlahTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jumlahTambahMouseClicked(evt);
            }
        });
        getContentPane().add(jumlahTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 30, 30));

        btn_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_batalMouseClicked(evt);
            }
        });
        getContentPane().add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 340, 40));

        btn_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_barangMouseClicked(evt);
            }
        });
        getContentPane().add(btn_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 340, 40));

        frameBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/naqiku.popupFrames/Pop Up  tambah transaksi.png"))); // NOI18N
        getContentPane().add(frameBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 501));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jumlahTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlahTambahMouseClicked
        // TODO add your handling code here:
        int jmlBarang = Integer.parseInt(jumlahBarang.getText());
        jmlBarang += 1;
        jumlahBarang.setText(Integer.toString(jmlBarang));
        
    }//GEN-LAST:event_jumlahTambahMouseClicked

    private void jumlahKurangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlahKurangMouseClicked
        // TODO add your handling code here:
        int jmlBarang = Integer.parseInt(jumlahBarang.getText());
        if (jmlBarang > 0) {
            jmlBarang -= 1;
        }
        jumlahBarang.setText(Integer.toString(jmlBarang));
    }//GEN-LAST:event_jumlahKurangMouseClicked

    private void btn_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_barangMouseClicked
        // TODO add your handling code here:
        String sql = "INSERT INTO transaksi_penjualan (kd_barang, qty) VALUES ('"+transaksiForm.kd_barang+"', "+jumlahBarang.getText()+");";
        try {            
        Config.eksekusi(sql);
        this.setVisible(false);
        JOptionPane.showMessageDialog(this, "Berhasil!");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_barangMouseClicked

    private void btn_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_batalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_batalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popupTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popupTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popupTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popupTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popupTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_barang;
    private javax.swing.JLabel btn_batal;
    private javax.swing.JLabel frameBackground;
    private javax.swing.JLabel hargaBarang;
    private javax.swing.JLabel jumlahBarang;
    private javax.swing.JLabel jumlahKurang;
    private javax.swing.JLabel jumlahTambah;
    private javax.swing.JLabel namaBarang;
    private javax.swing.JLabel warnaBarang;
    // End of variables declaration//GEN-END:variables
}
