/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package naqiku.applicationPopups;

import java.awt.Color;

/**
 *
 * @author Susa
 */
public class popupBarang extends javax.swing.JFrame {

    /**
     * Creates new form popupBarang
     */
    public popupBarang() {
        initComponents();
        invisTXT();
    }

    private void invisTXT(){
        txt_bahan.setBackground(new Color(0, 0, 0, 0));
        txt_hargaBeli.setBackground(new Color(0, 0, 0, 0));
        txt_hargaJual.setBackground(new Color(0, 0, 0, 0));
        txt_kodeBarang.setBackground(new Color(0, 0, 0, 0));
        txt_nama.setBackground(new Color(0, 0, 0, 0));
        txt_size.setBackground(new Color(0, 0, 0, 0));
        txt_stock.setBackground(new Color(0, 0, 0, 0));
        txt_warna.setBackground(new Color(0, 0, 0, 0));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_tambah_edit = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_warna = new javax.swing.JTextField();
        txt_bahan = new javax.swing.JTextField();
        txt_size = new javax.swing.JTextField();
        txt_hargaJual = new javax.swing.JTextField();
        txt_hargaBeli = new javax.swing.JTextField();
        txt_stock = new javax.swing.JTextField();
        txt_kodeBarang = new javax.swing.JTextField();
        box_jenis = new rojerusan.RSComboMetro();
        btn_jenis = new javax.swing.JLabel();
        frameBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(btn_tambah_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 240, 30));

        txt_nama.setBorder(null);
        txt_nama.setOpaque(false);
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 170, 30));

        txt_warna.setBorder(null);
        txt_warna.setOpaque(false);
        getContentPane().add(txt_warna, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 170, 30));

        txt_bahan.setBorder(null);
        txt_bahan.setOpaque(false);
        getContentPane().add(txt_bahan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 170, 30));

        txt_size.setBorder(null);
        txt_size.setOpaque(false);
        getContentPane().add(txt_size, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 170, 30));

        txt_hargaJual.setBorder(null);
        txt_hargaJual.setOpaque(false);
        getContentPane().add(txt_hargaJual, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 170, 30));

        txt_hargaBeli.setBorder(null);
        txt_hargaBeli.setOpaque(false);
        getContentPane().add(txt_hargaBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 170, 30));

        txt_stock.setBorder(null);
        txt_stock.setOpaque(false);
        getContentPane().add(txt_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 170, 30));

        txt_kodeBarang.setBorder(null);
        txt_kodeBarang.setOpaque(false);
        getContentPane().add(txt_kodeBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 170, 30));

        box_jenis.setColorArrow(new java.awt.Color(255, 255, 153));
        box_jenis.setColorBorde(new java.awt.Color(255, 255, 153));
        box_jenis.setColorFondo(new java.awt.Color(255, 255, 153));
        getContentPane().add(box_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 140, 40));
        getContentPane().add(btn_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 20, 20));

        frameBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/naqiku.popupFrames/Pop Up Edit & Tambah Barang.png"))); // NOI18N
        getContentPane().add(frameBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popupBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popupBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popupBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popupBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popupBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSComboMetro box_jenis;
    private javax.swing.JLabel btn_jenis;
    private javax.swing.JLabel btn_tambah_edit;
    private javax.swing.JLabel frameBackground;
    private javax.swing.JTextField txt_bahan;
    private javax.swing.JTextField txt_hargaBeli;
    private javax.swing.JTextField txt_hargaJual;
    private javax.swing.JTextField txt_kodeBarang;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_size;
    private javax.swing.JTextField txt_stock;
    private javax.swing.JTextField txt_warna;
    // End of variables declaration//GEN-END:variables
}
