/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package naqiku.application;

/**
 *
 * @author Susa
 */
public class dataTokoPembelian extends javax.swing.JFrame {

    /**
     * Creates new form dataTokoPembelian
     */
    public dataTokoPembelian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_logout = new javax.swing.JLabel();
        btn_barang = new javax.swing.JLabel();
        btn_supplier = new javax.swing.JLabel();
        btn_transaksi = new javax.swing.JLabel();
        btn_pengaturan = new javax.swing.JLabel();
        btn_datatoko = new javax.swing.JLabel();
        btn_penjualan = new javax.swing.JLabel();
        btn_keuntungan = new javax.swing.JLabel();
        btn_pembelian = new javax.swing.JLabel();
        frameBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, 70, 80));
        getContentPane().add(btn_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 200, 80));
        getContentPane().add(btn_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 200, 80));
        getContentPane().add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 200, 90));
        getContentPane().add(btn_pengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 200, 60));
        getContentPane().add(btn_datatoko, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 200, 70));
        getContentPane().add(btn_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 30, 130, 40));
        getContentPane().add(btn_keuntungan, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 150, 40));
        getContentPane().add(btn_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 30, 130, 40));

        frameBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/naqiku.frames/Data Toko Pembelian.png"))); // NOI18N
        getContentPane().add(frameBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataTokoPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataTokoPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataTokoPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataTokoPembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataTokoPembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_barang;
    private javax.swing.JLabel btn_datatoko;
    private javax.swing.JLabel btn_keuntungan;
    private javax.swing.JLabel btn_logout;
    private javax.swing.JLabel btn_pembelian;
    private javax.swing.JLabel btn_pengaturan;
    private javax.swing.JLabel btn_penjualan;
    private javax.swing.JLabel btn_supplier;
    private javax.swing.JLabel btn_transaksi;
    private javax.swing.JLabel frameBackground;
    // End of variables declaration//GEN-END:variables
}
